Лабораторная работа 1
TSVmegaproger228/Labs pull request #1
Opened 2024-10-19 18:46 UTC by TSVmegaproger228

2024-10-20 09:23 UTC, rmushkin requested changes
Поправьте, пожалуйста, файлы. Будут вопросы - пишите!

2024-10-20 09:23 UTC, rmushkin commented on Лабораторная работа 1/task_2.py
> +value = int(volume//book)
[PEP8](https://peps.python.org/pep-0008/):
1. Нужны пробелы вокруг математических операторов.
2. "value" - слишком общее слово для этого конкретного места

2024-10-20 09:23 UTC, rmushkin commented on Лабораторная работа 1/task_1.py
> +sum_ = sum(numbers[:4] + numbers[5:])
🔥 🔥 🔥  Вы не потеряли доступ ко встроенной функции `sum`, как некоторые ваши коллеги, поздравляю!

Тем не менее, выбор имени не совсем удачен. [PEP8](https://peps.python.org/pep-0008/) (указания по стилю написания кода) предписывает осмысленное именование переменных. Так что лучше добавить не просто подчёркивание, а какое-то уточняющее слово английского языка.

2024-10-20 09:23 UTC, rmushkin commented on Лабораторная работа 1/task_1.py
> +midd = sum_/length
[PEP8](https://peps.python.org/pep-0008/): вокруг математических операторов нужны пробелы

2024-10-22 22:13 UTC, rmushkin requested changes
Последний рывок, пожалуйста!

P. S. и дайте мне, пожалуйста, доступ на запись в репозиторий, чтобы я мог принять и закрыть.

2024-10-22 22:13 UTC, rmushkin commented on Лабораторная работа 1/task_1.py
> +midd = sumofnumbs / length
Ну вс хорошо, кроме того, что `midd` - не корректное английское слово, а sumonumbs - вообще не слово, а кашица из сокращений.
[PEP8](https://peps.python.org/pep-0008/) (указания по стилю написания кода):
> Function names should be lowercase, with words separated by underscores as necessary to improve readability.
>
> Variable names follow the same convention as function names.

2024-10-24 16:54 UTC, TSVmegaproger228 commented on Лабораторная работа 1/task_1.py
> +midd = sumofnumbs / length
Я возможно не так понял - "P. S. и дайте мне, пожалуйста, доступ на запись в репозиторий, чтобы я мог принять и закрыть.", поправьте, пожалуйста, если это так.(я просто добавил вас в "Collaborators")

2024-10-25 08:37 UTC, rmushkin commented on Лабораторная работа 1/task_1.py
> +midd = sumofnumbs / length
Теперь доступ есть. Извините, если сразу был, а я не заметил.

2024-10-25 08:38 UTC, merged